### ISSUE TITLE
خطای کلمه

### ISSUE THREAD

**Issue by wowrainyman** [VahidN/EnglishToPersianDictionaries#1]
در فایل 
https://github.com/VahidN/EnglishToPersianDictionaries/blob/master/Dictionaries/computer/A.json
خط
1334

    {
      "EnglishWord": "automatic date processing",
      "Meanings": [
        "پردازش اتوماتیک داده ها"
      ]
    },

date 
باید به
data
تبدیل گردد

**Comment by VahidN** [comment]
Thanks. Fixed via https://github.com/VahidN/EnglishToPersianDictionaries/commit/9f6cb50ea9cffd8683636d5d97b2d5c0e41ba7d0
